version: "3.7"
services:
    mysql:
        image: mysql:latest
        restart: always
        volumes:
            - ./mysql:/var/lib/mysql
        ports: 
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: gogs
            MYSQL_USER: gogs
            MYSQL_PASSWORD: gogs
    jenkins:
        image: jenkins/jenkins:lts
        privileged: true
        user: root
        ports:
            - 8080:8080
            - 50000:50000
        container_name: jenkins
        # check that the ~/jenkins directory exist    
        volumes:
            - ~/unix/jenkins:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
            - /usr/local/bin/docker:/usr/local/bin/docker
    
    gogs:
        image: gogs/gogs:latest
        volumes:
             - ./gogs:/data
        ports:
             - "222:22"
             - "3000:3000"
        depends_on:
             - mysql
        links:
             - mysql
